name: test20052025
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  provider: ^6.1.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  mockito: ^5.4.5
  json_serializable: ^6.9.5

dependency_overrides:
  analyzer: ^6.9.0
  json_serializable: ^6.9.5
  flutter_lints: ^5.0.0
